version: '3.8'

services:
  fs-server:
    build: .
    container_name: fs-server
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=fsdb
      - ROOT_USER_EMAIL=admin@gmail.com
      - ROOT_USER_PASSWORD=admin123
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - '6379:6379'
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fsdb
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: